export const mockedProducts = [
    {
        id: '0',
        brand: "Bacardi Light Rum",
        description: "Ron Blanco Bacardi",
        category: "Drinks",
        price: 5000,
        stock: 100,
        image: "https://www.thecocktaildb.com/images/ingredients/Light%20Rum.png",
    },
    {
        id: '1',
        brand: "Michters Bourbon",
        description: "Bourbon Mitchers",
        category: "Drinks",
        price: 9000,
        stock: 30,
        image: "https://www.thecocktaildb.com/images/ingredients/Bourbon.png",
    },
    {
        id: '2',
        brand: "Angostura Bitters",
        description: "Aromatizante Bitters Angostura",
        category: "Accesories",
        price: 2000,
        stock: 200,
        image: "https://www.thecocktaildb.com/images/ingredients/Angostura%20Bitters.png",
    },
    {
        id: '3',
        brand: "Sierra Mexican Tequila  ",
        description: "Tequila Sierra Mexicano",
        category: "Drinks",
        price: 9000,
        stock: 12,
        image: "https://www.thecocktaildb.com/images/ingredients/Tequila.png",
        largeDescription: "Sierra Tequila Silver es elaborado bajo los estrictos requerimientos del Gobierno Mexicano en Guadalajara, en la destilería Sierra Unidas de C. V. La destilería utiliza agave azul cultivado en campos naturales de las tierras altas como base para el tequila."
    },
    {
        id: '4',
        brand: "Plymouth English Gin",
        description: "Gin Inglés Plymouth",
        category: "Drinks",
        price: 11000,
        stock: 2,
        image: "https://www.thecocktaildb.com/images/ingredients/Gin.png",
    },
    {
        id: '5',
        brand: "Smirnoff Vodka",
        description: "Vodka Smirnoff",
        category: "Drinks",
        price: 3000,
        stock: 200,
        image: "https://www.thecocktaildb.com/images/ingredients/Vodka.png",
    },
    {
        id: '6',
        brand: "Dr Pepper",
        description: "Soda Dr Pepper",
        category: "Soft Drinks",
        price: 800,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Dr.%20Pepper.png",
    },
    {
        id: '7',
        brand: "The Berry Company",
        description: "Jugo de cerezas",
        category: "Soft Drinks",
        price: 1200,
        stock: 300,
        image: "https://www.thecocktaildb.com/images/ingredients/Cranberry%20Juice.png",
    },
    {
        id: '8',
        brand: "Martini",
        description: "Vermut seco",
        category: "Aperitive",
        price: 1800,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Dry%20Vermouth.png",
    },
    {
        id: '9',
        brand: "Disaronno",
        description: "Amaretto",
        category: "Drinks",
        price: 800,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Amaretto.png",
    },
    {
        id: '10',
        brand: "Bacardi",
        description: "Ron 151° Bacardi",
        category: "Drinks",
        price: 2800,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/151%20proof%20rum.png",
    },
    {
        id: '11',
        brand: "Absolut",
        description: "Vodka sabor limón Absolut",
        category: "Drinks",
        price: 8000,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Absolut%20citron.png",
    },
    {
        id: '12',
        brand: "Limón",
        description: "Limón por kilo",
        category: "Accesories",
        price: 180,
        stock: 100,
        image: "https://www.thecocktaildb.com/images/ingredients/lemon.png",
    },
    {
        id: '13',
        brand: "Myst",
        description: "Agua purificada Myst",
        category: "Soft Drinks",
        price: 1000,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Water.png",
    },
    {
        id: '14',
        brand: "Absolut",
        description: "Vodka sabor limón Absolut",
        category: "Drinks",
        price: 8000,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Absolut%20citron.png",
    },
    {
        id: '15',
        brand: "Naranja",
        description: "Naranja por kilo",
        category: "Accesories",
        price: 300,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Orange%20Peel.png",
    },
    {
        id: '16',
        brand: "Campari",
        description: "Campari",
        category: "Aperitive",
        price: 1300,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Campari.png",
    },
    {
        id: '17',
        brand: "Polar",
        description: "Soda premium Polar",
        category: "Soft Drinks",
        price: 1300,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Soda%20Water.png",
    },
    {
        id: '18',
        brand: "Proseco",
        description: "Vino blanco Italiano",
        category: "Wines",
        price: 1300,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Prosecco.png",
    },
    {
        id: '19',
        brand: "Aperol",
        description: "Aperitivo Aperol",
        category: "Aperitive",
        price: 2300,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Aperol.png",
    },
    {
        id: '20',
        brand: "Finest Call",
        description: "Jugo de limón premium",
        category: "Accesories",
        price: 2300,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Lime%20Juice.png",
    },
    {
        id: '21',
        brand: "Finest Call",
        description: "Jugo de limón premium",
        category: "Accesories",
        price: 2300,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Lime%20Juice.png",
    },
    {
        id: '22',
        brand: "Tropicana",
        description: "Jugo de naranja Tropicana",
        category: "Soft Drinks",
        price: 1000,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Lime%20Juice.png",
    },
    {
        id: '23',
        brand: "Cinnamon",
        description: "Canela por 100 gramos",
        category: "Accesories",
        price: 200,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Lime%20Juice.png",
    },
    {
        id: '24',
        brand: "Menta",
        description: "Menta por 100 gramos",
        category: "Accesories",
        price: 100,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Mint.png",
    },
    {
        id: '25',
        brand: "Lima",
        description: "Lima por kilo",
        category: "Accesories",
        price: 100,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Lime.png",
    },
    {
        id: '26',
        brand: "Hielo",
        description: "Bolsa de hielo",
        category: "Accesories",
        price: 100,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Ice.png",
    },
    {
        id: '27',
        brand: "Madagascar",
        description: "Extracto de vainilla premium",
        category: "Accesories",
        price: 100,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Vanilla%20extract.png",
    },
    {
        id: '28',
        brand: "Baileys",
        description: "Licor Baileys Original",
        category: "Drinks",
        price: 100,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Irish%20cream.png",
    },
    {
        id: '29',
        brand: "Fresh Yogurth",
        description: "Yogurth premium",
        category: "Accesories",
        price: 100,
        stock: 500,
        image: "https://www.thecocktaildb.com/images/ingredients/Yoghurt.png",
    },




]